spring:
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
  application:
    name: srping-tutorial
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airport
    username: postgres
    password: sonha12
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      schema: public
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
        default_schema: gtel
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8088
  servlet:
    context-path: /api
logging:
  level:
    com.gtel: debug

jwt:
  prefix: Bearer
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  refreshSecret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  validity: 86400
